import { app, dialog, ipcMain, shell, nativeImage } from 'electron'
import type { BrowserWindow, IpcMainInvokeEvent } from 'electron'
import { spawn } from 'node:child_process'
import { randomUUID } from 'node:crypto'
import { isAbsolute, basename, extname, join } from 'node:path'
import { readFile, stat, unlink } from 'node:fs/promises'
import JSZip from 'jszip'
import type { CoreHost } from './core-host'
import type { SecretStore } from './secrets'
import type { DesignExportFormat, InstallWslResult, VideoExportOptions } from '../shared/desktop-api'
import type { ProviderId } from '../shared/protocol'
import { exportDesign } from './design-export'
import { FFMPEG_MISSING, VIDEO_LIMITS, findFfmpeg, queueRecording } from './video-export'
import { encodePreviewPath, previewUrl } from '../shared/design-bridge'
import { listSystemFonts } from './system-fonts'
import iconPath from '../../resources/icon.png?asset'
import windowIconPath from '../../resources/icon.ico?asset'

export interface RegisterIpcDeps {
  core: CoreHost
  secrets: SecretStore
  getWindow: () => BrowserWindow | null
  dataDir: string
}

const PREVIEW_UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

/** Renderer frames may only be the app's own packaged file or, in dev, the Vite dev server. */
function assertTrustedSender(event: IpcMainInvokeEvent): void {
  const url = event.senderFrame?.url ?? ''
  const devUrl = process.env.ELECTRON_RENDERER_URL
  const trusted = url.startsWith('file://') || (devUrl != null && url.startsWith(devUrl))
  if (!trusted) throw new Error('Untrusted sender')
}

// ---- WSL elevation (setup wizard) ----
//
// The only command this app ever runs elevated: `wsl.exe --install --no-distribution`. The script
// below is a fixed string built entirely in this module — the renderer passes no arguments to
// `engine:installWsl`, so nothing it supplies ever reaches a shell.

const WSL_INSTALL_TIMEOUT_MS = 5 * 60_000

/** What the fixed script writes to its result file: the elevated `wsl.exe` process's own exit code,
 *  or how `Start-Process -Verb RunAs` itself failed (declined prompt vs. something else going wrong). */
type WslScriptResult = { outcome: 'exited'; exitCode: number } | { outcome: 'cancelled' } | { outcome: 'error'; message: string }

/**
 * Builds the one fixed PowerShell script `installWsl` ever runs. It always runs exactly
 * `wsl.exe --install --no-distribution`, elevated through `Start-Process -Verb RunAs` (the actual UAC
 * prompt), and writes its outcome to `resultPath` as JSON instead of stdout — Windows PowerShell's
 * redirected-output encoding is inconsistent enough (see `engine.ts`'s own notes on `wsl.exe`'s UTF-16
 * output) that a file this process reads back itself is the only reliable way to get a clean result.
 * `resultPath` is generated by this module, never by the renderer.
 */
function buildWslInstallScript(resultPath: string): string {
  const escapedPath = resultPath.replace(/'/g, "''")
  return `
$ErrorActionPreference = 'Stop'
$resultPath = '${escapedPath}'
try {
  $proc = Start-Process -FilePath 'wsl.exe' -ArgumentList @('--install','--no-distribution') -Verb RunAs -Wait -PassThru -WindowStyle Hidden
  $result = @{ outcome = 'exited'; exitCode = $proc.ExitCode } | ConvertTo-Json -Compress
} catch {
  $ex = $_.Exception
  $native = $null
  try { $native = $ex.NativeErrorCode } catch {}
  if (-not $native -and $ex.InnerException) { try { $native = $ex.InnerException.NativeErrorCode } catch {} }
  $text = $ex.ToString()
  if ($native -eq 1223 -or $text -match '1223' -or $text -match '(?i)cancel') {
    $result = @{ outcome = 'cancelled' } | ConvertTo-Json -Compress
  } else {
    $result = @{ outcome = 'error'; message = $ex.Message } | ConvertTo-Json -Compress
  }
}
[System.IO.File]::WriteAllText($resultPath, $result, (New-Object System.Text.UTF8Encoding($false)))
`.trim()
}

/** Runs `powershell.exe -EncodedCommand <script>` to completion. This outer process is never itself
 *  elevated — only the `wsl.exe` launch inside the script is, through its own `Start-Process -Verb
 *  RunAs`. Rejects on a spawn failure, a non-zero exit, or exceeding `timeoutMs`; the script's JSON
 *  result file (read by the caller) is what actually distinguishes success from cancel from error. */
function runPowerShellScript(script: string, timeoutMs: number): Promise<void> {
  // -EncodedCommand takes base64 of UTF-16LE, which sidesteps every quoting/escaping pitfall of
  // passing a multi-line script through argv.
  const encoded = Buffer.from(script, 'utf16le').toString('base64')
  return new Promise((resolve, reject) => {
    const child = spawn(
      'powershell.exe',
      ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-EncodedCommand', encoded],
      { windowsHide: true, stdio: 'ignore' }
    )

    let timedOut = false
    const timer = setTimeout(() => {
      timedOut = true
      child.kill()
    }, timeoutMs)

    child.on('error', (error) => {
      clearTimeout(timer)
      reject(error)
    })
    child.on('close', (code) => {
      clearTimeout(timer)
      if (timedOut) reject(new Error('This is taking too long and was stopped.'))
      else if (code === 0) resolve()
      else reject(new Error(`powershell.exe exited with code ${code}`))
    })
  })
}

let wslInstallInFlight: Promise<InstallWslResult> | null = null

/** Runs the one fixed elevation command this app ever runs, through a Windows administrator prompt:
 *  `wsl.exe --install --no-distribution`. Never rejects just because the user declined the prompt —
 *  that's `cancelled`, a choice they made, not a failure. A second call while one is already running
 *  joins the same promise instead of opening a second UAC prompt. */
function installWsl(): Promise<InstallWslResult> {
  if (!wslInstallInFlight) {
    wslInstallInFlight = doInstallWsl().finally(() => {
      wslInstallInFlight = null
    })
  }
  return wslInstallInFlight
}

async function doInstallWsl(): Promise<InstallWslResult> {
  const resultPath = join(app.getPath('temp'), `deskmates-wsl-install-${randomUUID()}.json`)

  try {
    await runPowerShellScript(buildWslInstallScript(resultPath), WSL_INSTALL_TIMEOUT_MS)
  } catch (error) {
    return { outcome: 'error', message: `Couldn't start the installer: ${error instanceof Error ? error.message : String(error)}` }
  }

  try {
    const raw = await readFile(resultPath, 'utf8')
    const parsed = JSON.parse(raw) as WslScriptResult
    if (parsed.outcome === 'cancelled') return { outcome: 'cancelled' }
    if (parsed.outcome === 'error') return { outcome: 'error', message: parsed.message || 'Something went wrong installing WSL.' }
    if (parsed.outcome === 'exited' && parsed.exitCode === 0) return { outcome: 'needs-restart' }
    if (parsed.outcome === 'exited') {
      return {
        outcome: 'error',
        message: `wsl.exe exited with code ${parsed.exitCode}. Try again, or run "wsl --install --no-distribution" from an administrator PowerShell window yourself.`
      }
    }
    return { outcome: 'error', message: "The installer's result wasn't understood. Try again." }
  } catch {
    return {
      outcome: 'error',
      message:
        'The installer closed without reporting what happened. Try again, or run "wsl --install --no-distribution" from an administrator PowerShell window yourself.'
    }
  } finally {
    await unlink(resultPath).catch(() => undefined)
  }
}

export function registerIpc({ core, secrets, getWindow, dataDir }: RegisterIpcDeps): void {
  ipcMain.handle('core:connection', (event) => {
    assertTrustedSender(event)
    return core.connectionInfo()
  })

  ipcMain.handle('secrets:status', (event) => {
    assertTrustedSender(event)
    return secrets.status()
  })

  ipcMain.handle('secrets:set', async (event, provider: ProviderId, key: string | null) => {
    assertTrustedSender(event)
    const result = await secrets.set(provider, key)
    core.sendKeys()
    return result
  })

  ipcMain.handle('dialog:pickFolder', async (event) => {
    assertTrustedSender(event)
    const window = getWindow()
    const result = window
      ? await dialog.showOpenDialog(window, { properties: ['openDirectory', 'createDirectory'] })
      : await dialog.showOpenDialog({ properties: ['openDirectory', 'createDirectory'] })
    if (result.canceled || result.filePaths.length === 0) return null
    return result.filePaths[0]
  })

  ipcMain.handle('shell:openPath', async (event, path: string) => {
    assertTrustedSender(event)
    if (!isAbsolute(path)) throw new Error('shell:openPath requires an absolute path')
    const error = await shell.openPath(path)
    if (error) throw new Error(error)
  })

  ipcMain.handle('app:autoStart:get', (event) => {
    assertTrustedSender(event)
    return app.getLoginItemSettings().openAtLogin
  })

  ipcMain.handle('app:autoStart:set', (event, enabled: boolean) => {
    assertTrustedSender(event)
    app.setLoginItemSettings({ openAtLogin: enabled, args: ['--hidden'] })
    return app.getLoginItemSettings().openAtLogin
  })

  ipcMain.handle('appearance:pickImage', async (event) => {
    assertTrustedSender(event)
    const window = getWindow()
    const result = window
      ? await dialog.showOpenDialog(window, { properties: ['openFile'], filters: [{ name: 'Images', extensions: ['png', 'svg', 'jpg', 'jpeg', 'webp'] }] })
      : await dialog.showOpenDialog({ properties: ['openFile'], filters: [{ name: 'Images', extensions: ['png', 'svg', 'jpg', 'jpeg', 'webp'] }] })
    if (result.canceled || result.filePaths.length === 0) return null
    
    const filePath = result.filePaths[0]
    const fileStat = await stat(filePath)
    if (fileStat.size > 2 * 1024 * 1024) throw new Error('Pick an image under 2 MB.')
    
    const ext = extname(filePath).toLowerCase().slice(1)
    const mime = ext === 'svg' ? 'image/svg+xml' : ext === 'jpg' ? 'image/jpeg' : `image/${ext}`
    const buffer = await readFile(filePath)
    return `data:${mime};base64,${buffer.toString('base64')}`
  })

  ipcMain.handle('appearance:pickFont', async (event) => {
    assertTrustedSender(event)
    const window = getWindow()
    const result = window
      ? await dialog.showOpenDialog(window, { properties: ['openFile'], filters: [{ name: 'Fonts', extensions: ['woff2', 'woff', 'ttf', 'otf'] }] })
      : await dialog.showOpenDialog({ properties: ['openFile'], filters: [{ name: 'Fonts', extensions: ['woff2', 'woff', 'ttf', 'otf'] }] })
    if (result.canceled || result.filePaths.length === 0) return null
    
    const filePath = result.filePaths[0]
    const fileStat = await stat(filePath)
    if (fileStat.size > 8 * 1024 * 1024) throw new Error('Pick a font file under 8 MB.')
    
    const ext = extname(filePath).toLowerCase().slice(1)
    const mime = ext === 'woff2' ? 'font/woff2' : ext === 'woff' ? 'font/woff' : ext === 'ttf' ? 'font/ttf' : 'font/otf'
    const buffer = await readFile(filePath)
    const name = basename(filePath, `.${ext}`)
    return { name, dataUrl: `data:${mime};base64,${buffer.toString('base64')}` }
  })

  ipcMain.handle('appearance:pickAnimation', async (event) => {
    assertTrustedSender(event)
    const window = getWindow()
    const result = window
      ? await dialog.showOpenDialog(window, { properties: ['openFile'], filters: [{ name: 'Animations', extensions: ['lottie', 'json'] }] })
      : await dialog.showOpenDialog({ properties: ['openFile'], filters: [{ name: 'Animations', extensions: ['lottie', 'json'] }] })
    if (result.canceled || result.filePaths.length === 0) return null
    
    const filePath = result.filePaths[0]
    const fileStat = await stat(filePath)
    if (fileStat.size > 5 * 1024 * 1024) throw new Error('Pick an animation under 5 MB.')
    
    const ext = extname(filePath).toLowerCase()
    const name = basename(filePath, ext)
    
    if (ext === '.json') {
      const json = await readFile(filePath, 'utf-8')
      return { name, json, fonts: [] }
    } else {
      const buffer = await readFile(filePath)
      let zip: JSZip
      try {
        zip = await JSZip.loadAsync(buffer)
      } catch {
        throw new Error("This file isn't a valid Lottie animation.")
      }

      const MAX_ANIMATION_JSON = 20 * 1024 * 1024
      const MAX_UNPACKED = 40 * 1024 * 1024
      let unpacked = 0
      const uncompressedSize = (file: JSZip.JSZipObject): number => {
        const data = (file as unknown as { _data?: { uncompressedSize?: number } })._data
        return typeof data?.uncompressedSize === 'number' ? data.uncompressedSize : 0
      }

      let manifest: any = {}
      const manifestFile = zip.file('manifest.json')
      if (manifestFile) {
        unpacked += uncompressedSize(manifestFile)
        if (unpacked > MAX_UNPACKED) throw new Error('This animation is too large once unpacked.')
        let manifestText: string
        try {
          manifestText = await manifestFile.async('string')
        } catch {
          throw new Error("This file isn't a valid Lottie animation.")
        }
        try {
          manifest = JSON.parse(manifestText)
        } catch {
          throw new Error("This file isn't a valid Lottie animation.")
        }
        if (manifest === null || typeof manifest !== 'object') {
          throw new Error("This file isn't a valid Lottie animation.")
        }
      }

      let animId = manifest.initial?.animation || manifest.animations?.[0]?.id || ''
      let animFile = animId ? (zip.file(`animations/${animId}.json`) || zip.file(`a/${animId}.json`)) : null

      if (!animFile) {
        const animFiles = zip.filter((path) => /^(animations|a)\/.*\.json$/.test(path))
        if (animFiles.length > 0) animFile = animFiles[0]
        else throw new Error("This file isn't a valid Lottie animation.")
      }

      const animSize = uncompressedSize(animFile)
      if (animSize > MAX_ANIMATION_JSON) throw new Error('This animation is too large once unpacked.')
      unpacked += animSize
      if (unpacked > MAX_UNPACKED) throw new Error('This animation is too large once unpacked.')
      let json: string
      try {
        json = await animFile.async('string')
      } catch {
        throw new Error("This file isn't a valid Lottie animation.")
      }

      const fonts: any[] = []
      const fontFiles = zip.filter((path, file) => !file.dir && /^(fonts|f)\//.test(path))
      for (const f of fontFiles) {
        unpacked += uncompressedSize(f)
        if (unpacked > MAX_UNPACKED) throw new Error('This animation is too large once unpacked.')
        let fontBuf: Buffer
        try {
          fontBuf = await f.async('nodebuffer')
        } catch {
          throw new Error("This file isn't a valid Lottie animation.")
        }
        const fontExt = extname(f.name).toLowerCase().slice(1) || 'ttf'
        const mime = fontExt === 'woff2' ? 'font/woff2' : fontExt === 'woff' ? 'font/woff' : fontExt === 'ttf' ? 'font/ttf' : 'font/otf'
        const fontName = basename(f.name, `.${fontExt}`)
        fonts.push({ name: fontName, dataUrl: `data:${mime};base64,${fontBuf.toString('base64')}` })
      }

      return { name, json, fonts }
    }
  })

  ipcMain.handle('appearance:setWindowIcon', (event, dataUrl: string | null) => {
    assertTrustedSender(event)
    const window = getWindow()
    if (!window) return
    if (dataUrl === null) {
      window.setIcon(process.platform === 'win32' ? windowIconPath : iconPath)
    } else if (typeof dataUrl === 'string' && dataUrl.startsWith('data:image/')) {
      window.setIcon(nativeImage.createFromDataURL(dataUrl))
    } else {
      throw new Error('setWindowIcon expects null or a data:image data URL')
    }
  })

  ipcMain.handle('design:export', async (event, projectId: string, format: DesignExportFormat, width?: number, file?: string) => {
    assertTrustedSender(event)
    if (typeof projectId !== 'string' || !PREVIEW_UUID_RE.test(projectId)) {
      throw new Error('That design was not found.')
    }
    if (format !== 'html' && format !== 'pdf' && format !== 'png') {
      throw new Error('The export format must be html, pdf or png.')
    }
    const pageWidth = width ?? 1440
    if (!Number.isInteger(pageWidth) || pageWidth < 320 || pageWidth > 3840) {
      throw new Error('The export width must be a whole number between 320 and 3840.')
    }
    if (file !== undefined && (typeof file !== 'string' || !/\.html?$/i.test(file) || file.length > 512)) {
      throw new Error('Only .html pages of a design can be exported.')
    }
    return exportDesign({ dataDir, projectId, format, width: pageWidth, parent: getWindow(), file })
  })

  let videoAbort: AbortController | null = null

  ipcMain.handle('design:exportVideo', async (event, projectId: string, file: string, options: VideoExportOptions) => {
    assertTrustedSender(event)
    if (typeof projectId !== 'string' || !PREVIEW_UUID_RE.test(projectId)) throw new Error('That design was not found.')
    if (typeof file !== 'string' || !/\.html?$/i.test(file) || file.length > 512) throw new Error('Only .html pages of a design can be recorded.')
    const format = options?.format
    if (format !== 'mp4' && format !== 'webm' && format !== 'gif') throw new Error('The video format must be mp4, webm or gif.')
    const whole = (value: unknown, min: number, max: number, label: string): number | undefined => {
      if (value === undefined || value === null) return undefined
      if (typeof value !== 'number' || !Number.isFinite(value) || value < min || value > max) throw new Error(`${label} must be between ${min} and ${max}.`)
      return value
    }
    const width = whole(options.width, VIDEO_LIMITS.minSide, VIDEO_LIMITS.maxSide, 'The width')
    const height = whole(options.height, VIDEO_LIMITS.minSide, VIDEO_LIMITS.maxSide, 'The height')
    const fps = whole(options.fps, 1, VIDEO_LIMITS.maxFps, 'The frame rate')
    const duration = whole(options.duration, 0.1, VIDEO_LIMITS.maxSeconds, 'The length in seconds')
    if (!findFfmpeg()) throw new Error(FFMPEG_MISSING)

    const base = (file.split('/').pop() ?? 'Design').replace(/\.(dc\.)?html?$/i, '') || 'Design'
    const parent = getWindow()
    const filters = [{ name: format === 'gif' ? 'GIF animation' : `${format.toUpperCase()} video`, extensions: [format] }]
    const choice = parent
      ? await dialog.showSaveDialog(parent, { defaultPath: `${base}.${format}`, filters })
      : await dialog.showSaveDialog({ defaultPath: `${base}.${format}`, filters })
    if (choice.canceled || !choice.filePath) return null

    videoAbort?.abort()
    const abort = new AbortController()
    videoAbort = abort
    const sender = event.sender
    let last = -1
    try {
      const result = await queueRecording({
        url: previewUrl(projectId, encodePreviewPath(file)),
        out: choice.filePath,
        format,
        width,
        height,
        fps,
        duration,
        signal: abort.signal,
        onProgress: (fraction) => {
          const percent = Math.floor(fraction * 100)
          if (percent === last || sender.isDestroyed()) return
          last = percent
          sender.send('design:videoProgress', fraction)
        }
      })
      return result.path
    } finally {
      if (videoAbort === abort) videoAbort = null
    }
  })

  ipcMain.handle('design:cancelVideo', (event) => {
    assertTrustedSender(event)
    videoAbort?.abort()
  })

  ipcMain.handle('design:systemFonts', async (event) => {
    assertTrustedSender(event)
    return listSystemFonts()
  })

  ipcMain.handle('engine:installWsl', (event) => {
    assertTrustedSender(event)
    return installWsl()
  })
}
